- name: Docker installation [Debian]
  import_tasks: docker-debian.yml
  when: ansible_facts['lsb']['id']|lower == 'debian'
- name: Docker installation [Ubuntu]
  import_tasks: docker-ubuntu.yml
  when: ansible_facts['lsb']['id']|lower == 'ubuntu'
- name: Docker installation [CentOS]
  import_tasks: docker-centos.yml
  when: ansible_facts['lsb']['id']|lower == 'centos'

- name: Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present
- name: Ensure user in docker group
  ansible.builtin.user:
    name: '{{ ansible_user }}'
    groups: docker
    append: yes
# Install compose switch v1 to v2 https://github.com/docker/compose-switch
- name: Install compose switch
  ansible.builtin.get_url:
    url: https://github.com/docker/compose-switch/releases/latest/download/docker-compose-linux-amd64
    dest: /usr/local/bin/docker-compose
    mode: '0755'
